### ISSUE TITLE
[bug] Render is flickering.

### ISSUE THREAD

**Issue by Gazyi** [SamVanheer/HL_Tools#1]
I see how it's load/unload triangles/lines every frame. 
Texture render is flickering too. 
![flickers](https://cloud.githubusercontent.com/assets/10533703/14954364/7b9ed5c0-107a-11e6-82aa-c6773012a92d.jpg)
I tried to make a video with problem but video doesn't show this problem.

**Comment by SamVanheer** [comment]
What are your pc specs? Are you using up to date graphics drivers? Something like this is probably caused by the graphics driver, since it works on my system with that model (HD HGrunt).

HLMV uses OpenGL 2.1, so if your system doesn't support it, that might be an issue.

**Comment by Gazyi** [comment]
I use 32 bit XP SP3 and use slightly unupdated NVIDIA drivers that support my GTX 260. I don't know what differences you did in rendering system, because Jed's HLMV work fine for me.

**Comment by SamVanheer** [comment]
This could be caused by wxWidgets or by the use of OpenGL 2.1. The original HLMV doesn't request a specific version, it just uses whatever the operating system provides. The code that draws everything is pretty much identical. Could you try using smooth or flat shaded render mode and see if that also has the problem? If not, it could be a problem in the code that handles textures.

**Comment by Gazyi** [comment]
It has same problem all render modes.

**Comment by SamVanheer** [comment]
Does this happen with all models or just specific ones? And could you take a screenshot of the entire window? The drawn polys information could help identify the cause.

**Comment by Gazyi** [comment]
http://imgur.com/a/pUpHZ
All missing model parts are flickering. Also all models have a flickering stripes.

**Comment by SamVanheer** [comment]
It's definitely sending polygons to the GPU. It sounds to me like the front and back buffer have different data in them, one has everything, the other doesn't, which would explain the flickering. Could you lower the FPS setting to its lowest and see if that affects the rate at which it flickers? You can change it in Tools->Options->General.

**Comment by Gazyi** [comment]
Yes, it affects on flickering rate.

**Comment by SamVanheer** [comment]
I've updated the download. I hope the changes i've made fix this problem.

**Comment by Gazyi** [comment]
Yes, looks like you fixed this issue. Thank you.

**Comment by SamVanheer** [comment]
Nice. Good to know that.
