### ISSUE TITLE
Use single shared user interface instance for each asset type

### ISSUE THREAD

**Issue by SamVanheer** [SamVanheer/HL_Tools#116]
Currently each loaded asset has its own instance of the user interface. This is somewhat expensive and also results in interface state that should be shared -like the ground texture- being isolated.

Ideally each asset provider has its own user interface instance that assets are added to. Switching assets through the tab bar switches both the UI widget and the active asset for that widget.

The work required for this also enables #68 to work since asset-specific state has to be stored off somewhere. This makes refreshing the asset data much easier.

**Comment by Solokiller** [comment]
This is unnecessary and would complicate things too much.

**Comment by Solokiller** [comment]
This is necessary to support the persisting of dock layouts. Required for #205 to be implementable.

**Comment by SamVanheer** [comment]
This has been implemented.
