### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by SamVanheer** [SamVanheer/HL_Tools#127]
See Shepard's work for things that need doing: https://github.com/Solokiller/HL_Tools/compare/dev...JoelTroch:feature/linux

**Comment by MegaBrutal** [comment]
Would be highly appreciated! Tell me if there is a way to help.
Any Windows-dependent libraries currently used?

**Comment by SamVanheer** [comment]
Nothing exclusive to Windows, but one of the libraries (GLEW) will be removed once i've upgraded everything to use shaders since Qt's OpenGL APIs provide what's needed.

The rest will need to be updated to work on Linux since i've only made Windows builds for Ogg, Vorbis and VorbisFile. I haven't looked into what that's going to take, but i don't expect it will be too complicated.

I'd want to look into getting those libraries from a package manager like vcpkg or Conan if possible.

**Comment by SamVanheer** [comment]
Duplicate of #10.
