### ISSUE TITLE
Bug when loading a model which lenght-size does not match due to extra emtpy-lines.

### ISSUE THREAD

**Issue by metita** [SamVanheer/HL_Tools#176]
So basically if you manage to open a .mdl with Notepad++ and then you add empty lines, it will fail to open with HLMV.

If you have a model with size 10000 and then you add a empty-line inside the model info (not sure how to call this), HLMV will fail to open the asset because his size will be 10001 but HLMV just recognize it as 10000, removing empty-lines resolves the problem but maybe a workaround can be made on HLMV side.

Failed to load asset:
![image](https://user-images.githubusercontent.com/33007491/126948515-702d1939-d4f4-42c7-8396-95ce6787a096.png)

Fixed:
![image](https://user-images.githubusercontent.com/33007491/126948529-7d7497e4-8302-4a15-91dc-ea21656b00ad.png)

**Comment by Solokiller** [comment]
You shouldn't modify files that way. If you need to make changes, either change things in HLAM or decompile the model, change it and recompile it.

HLAM specifically checks the length member to make sure the model hasn't been incorrectly modified, so that's not changing.

**Comment by metita** [comment]
I know, the fact is that some people have no idea how to fix it by deleting empty lines and even less recompiling, they will just acknowledge that model may he corrupted, its fine I guess, maybe the model author did that as a protection measure.

**Comment by Solokiller** [comment]
There is no way to tell the difference between a corrupted model and a modified one, so i can't help with that either way.

**Comment by pierow** [comment]
I ran into this as well. For some reason some models have multiple new lines added to them at the end and HL displays the models fine.  Might've been some old software adding newlines or a protection measure.

**Comment by oskarlh** [comment]
@SamVanheer Might this be the same issue?... I tried to open [deathrun_brickwall](https://twhl.info/vault/view/5806)'s cstrike/models/Kicius/zuvis2.mdl in HLAM 1.3. It fails with
![image](https://user-images.githubusercontent.com/11921030/151666494-7f450df0-56de-486a-addb-2b1d65bc6233.png)
but both HLMV and Counter-Strike 1.6 load and render the model

**Comment by SamVanheer** [comment]
I'm going to rework model loading to avoid the use of the length field, instead more robust validation will be used that relies on file size checks to prevent invalid access. Note that this won't necessarily allow the models to load; Xash models re-purpose some data so it will be necessary to check for that and ask the user if they want to discard that data before loading.

For completeness users will be asked if they want to open the model in Paranoia 2 model viewer instead, which does support that data.

**Comment by SamVanheer** [comment]
Note: i've added a feature that redirects users to Xash Model Viewer (usually Paranoia 2 Model Viewer) if it is a Xash model.

For other models i'll add a more robust check that doesn't rely on the length field.

Do you have any models i can test with? Like Gamebanana links or something, models that are known to have this issue, not just ones that have been manually edited.

**Comment by oskarlh** [comment]
@SamVanheer #232 (in case you forgot)

**Comment by SamVanheer** [comment]
Thanks.

**Comment by SamVanheer** [comment]
I've replaced the length check with validation logic which will protect against malformed models. Xash models are loaded by forwarding them to Xash model viewer (usually Paranoia 2 model viewer but that's up to the user) so this should be working properly now.

All of the models from deathrun_brickwall load now.

**Comment by oskarlh** [comment]
Awesome, thanks!
