### ISSUE TITLE
glGenerateMipmap is an OpenGL 3.0 API, needs replacing

### ISSUE THREAD

**Issue by SamVanheer** [SamVanheer/HL_Tools#207]
`glGenerateMipmap` was added with OpenGL 3.0, which means users whose driver only supports OpenGL 2.1 will not be able to run the program if mipmaps are enabled. A software implementation is needed to replace this API call.

**Comment by Solokiller** [comment]
This API is part of OpenGL ES 2.0 so it may be possible to rely on ANGLE to handle this instead.
