### ISSUE TITLE
Problem with win xp (HLMV)

### ISSUE THREAD

**Issue by dimaspaf14** [SamVanheer/HL_Tools#223]
i dont know what to start with, but i got bug that the texture wont display and just get blank.

The HLMV version 2.11 Beta001 is working for windows xp

Video:
 [Link](https://youtu.be/m7lePK5oOog)

**Comment by SamVanheer** [comment]
Can you try this to see if it works now: https://github.com/SamVanheer/HL_Tools/releases/tag/HLMV-V2.11-beta002

**Comment by dimaspaf14** [comment]
Its work now, thank you soo much, if theres any prob ill post it here :D

**Comment by SamVanheer** [comment]
Great, i'll release a new full build. Note that this version is no longer supported so if there is anything wrong it's unlikely i can provide support (the issues i've fixed were relatively simple).

**Comment by SamVanheer** [comment]
New version: https://github.com/SamVanheer/HL_Tools/releases/tag/HLMV-V2.11
