### ISSUE TITLE
Exported textures become corrupted

### ISSUE THREAD

**Issue by Komaedave** [SamVanheer/HL_Tools#238]
Sometimes, when exporting textures, I get a weird corrupted version instead of the desired one. 
![imagen](https://user-images.githubusercontent.com/30252009/167982253-6179f7df-7239-43ef-b570-f5381a70c15f.png)
This happens consistently. It can be tested by exporting the head texture from the scientist deathmatch model for HL1.

**Comment by SamVanheer** [comment]
Additional info from Discord: https://discord.com/channels/291678871856742400/484363370640703509/1028480654008139837

Affected graphics cards:
* amd rx 570
* GTX 750 1gb (driver version 512.15)
* NVIDIA GTX 1050 (not Ti) 4GB VRAM
* NVIDIA GeForce RTX 3060 (Driver Version: 31.0.15.1748 from the date 21/9/2022)

Seems to be random, could be a problem with `ConvertTextureToIndexed8Image` or `QImage` itself.
