### ISSUE TITLE
Window can't be resized to small sizes (horizontally)

### ISSUE THREAD

**Issue by Droooga** [SamVanheer/HL_Tools#250]
![kuva](https://user-images.githubusercontent.com/85588460/205442392-bb726cfa-4df3-4b52-966c-33a8b390142a.png)
Comparison between normal HLMV and HLAM.
In normal HLMV you can resize the window to be very small but in HLAM you can't.
This is kind of an issue for me since I keep both editing program and HLAM open to do quick texture fixes if theres any.
Correct me if i'm wrong but I guess this is a limitation with Qt?

**Comment by SamVanheer** [comment]
The minimum width of the window is determined by the widest panel. You can dock the panels to the left and right sides of the window to allow the window to shrink more.

I can look into making it possible to shrink the window even if it would cause parts of the panels to extend past the edges of the window.

I can also look into reworking the panels to make some of the bigger ones smaller. The Textures panel is the biggest and some of those options can be moved to the menu.

**Comment by SamVanheer** [comment]
I've reworked the UI to make things smaller to allow the window to shrink more. Additionally i've added options to toggle parts of the UI off to allow the window to shrink even more:
https://www.youtube.com/watch?v=elPt0m_hoh0

**Comment by SamVanheer** [comment]
Note that you can also do this with the fullscreen window. Open the window, press F11 to toggle it to windowed mode and then drag it to resize it. I've improved the fullscreen window a bit to make it more user-friendly and more efficient in 2.0.0.

**Comment by SamVanheer** [comment]
I've reworked the UI to reduce the width and height of panels as much as possible. Combined with the option to hide parts of the UI and switch to a scene-only view and fullscreen mode supporting arbitrary sizes it's possible to view the model while shaping the window to be any size.
