### ISSUE TITLE
Windows Builds

### ISSUE THREAD

**Issue by camjac251** [SamVanheer/HL_Tools#30]
I wasn't able to find any windows builds for this. Have you looked into Travis or Appveyor for automated builds after each commit?

Also, what version of HLMV is this based on? I was hoping to find a replacement to the SFM HLMV which crashes quite often and doesn't seem have to much support.

Does your model viewer support drag and drop? Or if you are opening an mdl file directly with the program, does it open quickly, unlike this SFM one.

**Comment by SamVanheer** [comment]
You can find windows builds in the first post of this thread: http://forums.svencoop.com/showthread.php/43768-Half-Life-Model-Viewer-2-0-Beta

This model viewer is built for GoldSource, not Source. It does support drag and drop support, and opens virtually instantaneously.

I haven't looked into automated builds yet as i have no experience with them, but thanks for the recommendation. When i have the time i'll see what i can do.

**Comment by camjac251** [comment]
Would you consider adding Source 1 support to it?

**Comment by SamVanheer** [comment]
My goal is to support GoldSource only. Source engine support would require a lot of work, and i have no experience with its model format.

**Comment by SamVanheer** [comment]
The current build can be found here: https://github.com/SamVanheer/HL_Tools/releases

Any future builds of this version of model viewer can be found there as well, but i'm planning to make a new version that will be located in another repository.
