### ISSUE TITLE
[HLMV] Limited frame rate

### ISSUE THREAD

**Issue by SPRKH** [SamVanheer/HL_Tools#38]
The frame rate in the viewport seems to be capped at around 32 fps, making animation playback appear less smooth than it could be. JLMV renders at up to 60 fps. Raising the limit to 60 fps, or higher, would be a welcome upgrade.

![framerate](https://cloud.githubusercontent.com/assets/20645814/17108458/eb7ec14c-5293-11e6-9f1e-05784ba03eb5.jpg)

**Comment by SamVanheer** [comment]
You can increase the framerate to 60 in the Options menu. If it's still capped, you'll have to wait until i've reworked the render loop so it relies on a better timing algorithm.

**Comment by SPRKH** [comment]
I totally overlooked that. My bad, case closed. Out of curiosity though: is there any particular reason why the default setting is 30 fps? I assume one would want the highest frame rate possible in most scenarios.

**Comment by SamVanheer** [comment]
The current render algorithm doesn't work so well when a lot of stuff is being drawn, like being unable to quit. I figured keeping the frame rate down a bit would help until that's fixed.

**Comment by SamVanheer** [comment]
I've reworked the render loop; the renderer can now render far more frames than before. On my system CS view models rendered at up to 300 FPS. The new maximum is 500, in case you want to try. I'll get a new version out today if possible.

**Comment by SamVanheer** [comment]
I've uploaded a new version; the download link can be found here: https://github.com/SamVanheer/HL_Tools/wiki/Half-Life-Model-Viewer

**Comment by SPRKH** [comment]
Cool, thanks for the update! This version introduces a new issue all-together though: when opening a .mdl file from explorer the program shows up, but does not load the model. You have to drag/drop the file into the window, or load it up manually.

**Comment by SamVanheer** [comment]
Thanks for reporting the issue; i've fixed it and will update the download shortly.

**Comment by SamVanheer** [comment]
I've updated the download.
