### ISSUE TITLE
[HLMV] Weapon Origin mismatch

### ISSUE THREAD

**Issue by SPRKH** [SamVanheer/HL_Tools#41]
Below is an image comparison of the weapon origins in JHLMV and in your version:

![origins](https://cloud.githubusercontent.com/assets/20645814/17277745/0cfd96b6-574b-11e6-8ccf-a57372f49e53.jpg)

JHLMV renders the weapon position accurately when looking straight ahead.
Your version seems to be more correct when looking straight down.

The way JHLMV renders the model gives a better impression of the positioning in-game (at least in vanilla HL) - tl;dr "make it like jhlmv."

**Comment by SamVanheer** [comment]
Thanks for reporting this, i'll take a look when i have time.

**Comment by SamVanheer** [comment]
2.7 fixes this issue.
