### ISSUE TITLE
Download for HLMV leads to a 404 page

### ISSUE THREAD

**Issue by RaraFolf** [SamVanheer/HL_Tools#48]
As title says, the download at 
https://dl.dropboxusercontent.com/u/46048979/HLMV_standalone.rar
currently leads to a 404 page.

**Comment by SamVanheer** [comment]
Thanks for the report, i've updated the link to this: https://www.dropbox.com/s/3j1r5sebsrbhzhq/HLMV_standalone.rar?dl=0

Let me know if it works.

**Comment by RaraFolf** [comment]
The new link works, thank you very much.
