### ISSUE TITLE
[HLMV] Add options for modifying/adding flags

### ISSUE THREAD

**Issue by KernCore91** [SamVanheer/HL_Tools#49]
Similiar to Paranoia 2's HLMV:

![](http://i.imgur.com/4yWpXCB.png)

More information about flags can be found here:
http://the303.org/tutorials/gold_qc.htm

**Comment by SamVanheer** [comment]
I implemented this as a new control panel. I tested it with the Human Grunt model (hgrunt.mdl) and i only saw blood particles.
I'm not sure if other effects will work, it's not something i can do anything about from model viewer itself.
