### ISSUE TITLE
[HLMV] Broken screenshot utility

### ISSUE THREAD

**Issue by GBCS-PRO** [SamVanheer/HL_Tools#58]
When I use the "take screenshot" tool it shows me the window to save the file with name and location etc.. But there's no default file type extension attached (like .bmp .tga etc..). 
However saving it with any image extension shows a broken screenshot like this:
![glawk](https://user-images.githubusercontent.com/50755959/57959010-7d47c480-790a-11e9-9119-92235f294af5.jpg)

**Comment by SamVanheer** [comment]
Can you provide the model you're using, since i don't have the perspective issue.

I'll see if i can make the file saving better.

**Comment by SamVanheer** [comment]
I've reworked the file save dialog to work properly as a save dialog, it also allows you to select different extensions.

Try the new build, see if the problem still happens: https://github.com/SamVanheer/HL_Tools/releases/tag/V2.8-P

Try different extensions to see if the problem is restricted to specific formats.

**Comment by GBCS-PRO** [comment]
I tried the new build .. The dialog is fixed but the utility of taking screenshots is still broken. I tried different models and different formats and the screenshots are still broken:
![awp](https://user-images.githubusercontent.com/50755959/57969645-f0d8e880-7981-11e9-8300-22db49e131b5.jpg)
![screenshot](https://user-images.githubusercontent.com/50755959/57969646-f0d8e880-7981-11e9-8481-f866c9f25b42.jpg)
here's the pistol model I used
[v_glock18.zip](https://github.com/SamVanheer/HL_Tools/files/3194054/v_glock18.zip)

**Comment by GBCS-PRO** [comment]
> I tried the new build .. The dialog is fixed but the utility of taking screenshots is still broken. I tried different models and different formats and the screenshots are still broken:
> ![awp](https://user-images.githubusercontent.com/50755959/57969645-f0d8e880-7981-11e9-8300-22db49e131b5.jpg)
> ![screenshot](https://user-images.githubusercontent.com/50755959/57969646-f0d8e880-7981-11e9-8481-f866c9f25b42.jpg)
> (The background color was the default one so that's why new screenshots look different..)
> here's the pistol model I used
> [v_glock18.zip](https://github.com/SamVanheer/HL_Tools/files/3194054/v_glock18.zip)

**Comment by SamVanheer** [comment]
I've uploaded another build: https://github.com/SamVanheer/HL_Tools/releases/tag/V2.8-P

I've changed two things that should help prevent what you're experiencing, try it out and see if it still happens.

**Comment by GBCS-PRO** [comment]
![screenshot](https://user-images.githubusercontent.com/50755959/57975810-ff52ee80-79d9-11e9-883f-874637fe8724.jpg)
Yup. It works perfectly now! Thanks for help..

**Comment by SamVanheer** [comment]
You're welcome :)
