### ISSUE TITLE
[HLMV] 2 Bugs..

### ISSUE THREAD

**Issue by GBCS-PRO** [SamVanheer/HL_Tools#59]
1. Several people have reported this for me. It seems that some options are going out of the screen on 1366x768. Is this fix-able?
![screen res bug](https://user-images.githubusercontent.com/50755959/57975844-aa63a800-79da-11e9-830e-0ee797551a6d.jpg)

2. Axis colors are darker if no other option was selected (except for backface culling):
![output_C9ykzU](https://user-images.githubusercontent.com/50755959/57981995-9904b500-7a47-11e9-918a-5a2cfc3f0d16.gif)

Also Axis is misspelled to "Axes"

**Comment by SamVanheer** [comment]
I've added scrollbars for when you can't see the entire control panel.
OpenGL settings for axis drawing have been corrected to always render correctly.

Axes is the plural form of axis, and the checkbox means to show all 3 axes so it isn't a typo.

You can try out the changes in this build: https://github.com/SamVanheer/HL_Tools/releases/tag/V2.8-P

Once you've confirmed it's fixed i can promote it to release.

**Comment by GBCS-PRO** [comment]
Well it's fixed but I found one more bug (lol)
When trying to export UV map the viewer stops responding and crashes..
