### ISSUE TITLE
Improve filesystem support

### ISSUE THREAD

**Issue by SamVanheer** [SamVanheer/HL_Tools#74]
The filesystem handles SteamPipe, but it still needs improvements.

- [x] HLAM should be able to auto-detect the Steam Half-Life installation using the registry key for it, and autodetect all mods installed for it.

- [x] This also requires support for non-Steam Half-Life installations such as WON Half-Life, Xash and Sven Co-op.

- [x] In addition, models loaded from a location that is not a mod directory should still support locating other files relative to its directory, like for example locating sounds that are located in the relative path `<models directory extracted from filename>/../sound`.

- [x] Language-specific directories should also be supported, and the user should be able to choose which one to use

**Comment by regener** [comment]
About "Language-specific directories":
Do you mean special characters like "é"?
I just noticed that it can't open a model if the folder is on my desktop (by OS sys language) it contains a "é" char :D

Of course I moved it elsewhere, just asking.

**Comment by Solokiller** [comment]
Language-specific directories means SteamPipe directories ending in `_<language>`, like `_french`.

I just released an update that allows you to open files that contain Unicode characters: https://github.com/Solokiller/HL_Tools/releases/tag/V2.9-beta003

**Comment by regener** [comment]
I see now.
Thank you for the update!

**Comment by SamVanheer** [comment]
These features have all been implemented.
